<a href="https://colab.research.google.com/github/rajeshkumar-niet/Machine_Learning/blob/main/Cross_Validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Import

### Importing Dependencies




In [51]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score

### Importing Models

In [52]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

## Data Preprocessing

In [53]:
dataset = pd.read_csv('/content/diabetes.csv')

In [54]:
dataset.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [55]:
dataset.shape
dataset.info()
dataset.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [56]:
dataset.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [57]:
dataset['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [58]:
X = dataset.drop(columns='Outcome', axis=1)
Y = dataset['Outcome']

In [59]:
print(X.shape, Y.shape)

(768, 8) (768,)


## Train Test Split

In [60]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [61]:
print(X_train.shape, X_test.shape)
print(Y_train.shape, Y_test.shape)

(614, 8) (154, 8)
(614,) (154,)


In [62]:
models = [LogisticRegression(max_iter=1000), SVC(kernel='linear'), KNeighborsClassifier(), RandomForestClassifier(), DecisionTreeClassifier()]

In [63]:

def compare_models_train_test():
  for model in models:

    model.fit(X_train, Y_train)

    test_data_prediction = model.predict(X_test)

    accuracy = accuracy_score(Y_test, test_data_prediction)

    print('Accuracy score of the ', model, ' = ', accuracy)

In [64]:
compare_models_train_test()

Accuracy score of the  LogisticRegression(max_iter=1000)  =  0.7597402597402597
Accuracy score of the  SVC(kernel='linear')  =  0.7727272727272727
Accuracy score of the  KNeighborsClassifier()  =  0.7272727272727273
Accuracy score of the  RandomForestClassifier()  =  0.7207792207792207
Accuracy score of the  DecisionTreeClassifier()  =  0.6948051948051948


## KFold

In [65]:
cross_val_lr = cross_val_score(LogisticRegression(max_iter=1000), X, Y, cv=5)
print(cross_val_lr)
mean_cross_lr = (sum(cross_val_lr)/len(cross_val_lr))*100
mean_cross_lr = round(mean_cross_lr, 2)
print("Accuracy of Linear Regression :",mean_cross_lr)

[0.77272727 0.74675325 0.75324675 0.81045752 0.77777778]
Accuracy of Linear Regression : 77.22


In [66]:
cross_val_svm = cross_val_score(SVC(kernel='linear'), X, Y, cv=5)
print(cross_val_svm)
mean_cross_svm = (sum(cross_val_svm)/len(cross_val_svm))*100
mean_cross_svm = round(mean_cross_svm, 2)
print("Accuracy of Support Vector Machine :",mean_cross_svm)

[0.75974026 0.75324675 0.74025974 0.81045752 0.76470588]
Accuracy of Support Vector Machine : 76.57


In [67]:
crss_val_KNN = cross_val_score(KNeighborsClassifier(), X, Y, cv=5)
print(crss_val_KNN)
mean_cross_knn = (sum(crss_val_KNN)/len(crss_val_KNN))*100
mean_cross_knn = round(mean_cross_knn, 2)
print("Accuracy of KNN :",mean_cross_knn)

[0.72727273 0.72727273 0.7012987  0.75816993 0.70588235]
Accuracy of KNN : 72.4


In [68]:
cross_val_rf = cross_val_score(RandomForestClassifier(n_estimators=100), X, Y, cv=5)
print(cross_val_rf)
mean_cross_rf = (sum(cross_val_rf)/len(cross_val_rf))*100
mean_cross_rf = round(mean_cross_rf, 2)
print("Accuracy of Random Forest :",mean_cross_rf)

[0.75324675 0.72077922 0.77922078 0.84313725 0.77124183]
Accuracy of Random Forest : 77.35


In [69]:
cross_val_dt = cross_val_score(DecisionTreeClassifier(), X, Y, cv=5)
print(cross_val_dt)
mean_cross_dt = (sum(cross_val_dt)/len(cross_val_dt))*100
mean_cross_dt = round(mean_cross_dt, 2)
print("Accuracy of Decision Tree :",mean_cross_dt)

[0.73376623 0.66883117 0.68831169 0.75163399 0.73856209]
Accuracy of Decision Tree : 71.62


In [70]:
models = [LogisticRegression(max_iter=1000), SVC(kernel='linear'), KNeighborsClassifier(), RandomForestClassifier(), DecisionTreeClassifier()]

In [71]:
def compare_models_cross_val():
    for model in models:
        cv_score = cross_val_score(model, X, Y, cv=5)
        mean_accuracy = sum(cv_score)/len(cv_score)
        mean_accuracy = mean_accuracy*100
        mean_accuracy = round(mean_accuracy, 2)
        print('Cross Validation accuracies for the ', model, ' = ', cv_score)
        print('Accuracy % of the ', model, ' = ', mean_accuracy, '\n')

In [72]:
compare_models_cross_val()

Cross Validation accuracies for the  LogisticRegression(max_iter=1000)  =  [0.77272727 0.74675325 0.75324675 0.81045752 0.77777778]
Accuracy % of the  LogisticRegression(max_iter=1000)  =  77.22 

Cross Validation accuracies for the  SVC(kernel='linear')  =  [0.75974026 0.75324675 0.74025974 0.81045752 0.76470588]
Accuracy % of the  SVC(kernel='linear')  =  76.57 

Cross Validation accuracies for the  KNeighborsClassifier()  =  [0.72727273 0.72727273 0.7012987  0.75816993 0.70588235]
Accuracy % of the  KNeighborsClassifier()  =  72.4 

Cross Validation accuracies for the  RandomForestClassifier()  =  [0.76623377 0.72077922 0.75974026 0.81699346 0.75816993]
Accuracy % of the  RandomForestClassifier()  =  76.44 

Cross Validation accuracies for the  DecisionTreeClassifier()  =  [0.68181818 0.65584416 0.7012987  0.78431373 0.71895425]
Accuracy % of the  DecisionTreeClassifier()  =  70.84 

